var objArray = { 
		"澄迈":[
		        {  
		        	sort:"icon_home_all@3x.png",
		            name:"59打印社",  
		            distance:"2.1",  
		            money:"15",  
		            fans:"1524",  
		            num:"3",
		            type:"文员",
		            type1:"wenyuan",
		            type2:"wy",
		            type3:"w"
		        },  
		        {  
		        	sort:"icon_home_clerk@3x.png",
		            name:"星期天办公大楼",  
		            distance:"2.2",  
		            money:"50",  
		            fans:"9524",  
		            num:"2",
		            type:"文员",
		            type1:"wenyuan",
		            type2:"wy",
		            type3:"w"
		        }, 
		        {  
		        	sort:"icon_home_collect@3x.png",
		            name:"老城菜市场",  
		            distance:"5.1",  
		            money:"25",  
		            fans:"6524",  
		            num:"3",
		            type:"采集",
		            type1:"caiji",
		            type2:"cj",
		            type3:"c"
		        }, 
		        {  
		        	sort:"icon_home_collect@3x.png",
		            name:"老城",  
		            distance:"5.2",  
		            money:"10",  
		            fans:"12524",  
		            num:"3",
		            type:"采集",
		            type1:"caiji",
		            type2:"cj",
		            type3:"c"
		        }, 
		        {  
		        	sort:"icon_home_collect@3x.png",
		            name:"老城娱乐商城",  
		            distance:"6.0",  
		            money:"80",  
		            fans:"15524",  
		            num:"2",
		            type:"娱乐",
		            type1:"yule",
		            type2:"yl",
		            type3:"y"
		        }
		    ],
		"北京":[
		        {  
		        	sort:"icon_home_min_store@3x.png",
		            name:"西单",  
		            distance:"2.1",  
		            money:"15",  
		            fans:"94524",  
		            num:"3",
		            type:"促销",
		            type1:"cuxiao",
		            type2:"cx",
		            type3:"c"
		        },  
		        {  
		        	sort:"icon_home_clerk@3x.png",
		            name:"星期天办公大楼",  
		            distance:"2.2",  
		            money:"50",  
		            fans:"9524",  
		            num:"2",
		            type:"文员",
		            type1:"wenyuan",
		            type2:"wy",
		            type3:"w"
		        }, 
		        {  
		        	sort:"icon_home_min_store@3x.png",
		            name:"西单菜市场",  
		            distance:"5.1",  
		            money:"25",  
		            fans:"652454",  
		            num:"3",
		            type:"采集",
		            type1:"caiji",
		            type2:"cj",
		            type3:"c"
		        }, 
		        {  
		        	sort:"icon_home_collect@3x.png",
		            name:"西单商城",  
		            distance:"5.2",  
		            money:"10",  
		            fans:"12524",  
		            num:"3",
		            type:"促销",
		            type1:"cuxiao",
		            type2:"cx",
		            type3:"c"
		        }, 
		        {  
		        	sort:"icon_home_collect@3x.png",
		            name:"西单地铁站",  
		            distance:"6.0",  
		            money:"80",  
		            fans:"15524",  
		            num:"3",
		            type:"交通",
		            type1:"jiaotong",
		            type2:"jt",
		            type3:"j"
		        },
		        {  
		        	sort:"icon_home_teaching@3x.png",
		            name:"清华大学",  
		            distance:"6.0",  
		            money:"80",  
		            fans:"15524",  
		            num:"2",
		            type:"教育",
		            type1:"jiaoyu",
		            type2:"jy",
		            type3:"j"
		        }
		    ],
		    "上海":[
		        {  
		        	sort:"icon_home_electricity@3x.png",
		            name:"陆家嘴",  
		            distance:"2.1",  
		            money:"15",  
		            fans:"9415424",  
		            num:"3",
		            type:"采集",
		            type1:"caiji",
		            type2:"cj",
		            type3:"c"
		        },  
		        {  
		        	sort:"icon_home_clerk@3x.png",
		            name:"星期天办公大楼",  
		            distance:"2.2",  
		            money:"50",  
		            fans:"9524",  
		            num:"2",
		            type:"文员",
		            type1:"wenyuan",
		            type2:"wy",
		            type3:"w"
		        }, 
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"外滩",  
		            distance:"5.1",  
		            money:"25",  
		            fans:"65454",  
		            num:"3",
		            type:"采集",
		            type1:"caiji",
		            type2:"cj",
		            type3:"c"
		        }, 
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"外滩商城",  
		            distance:"5.2",  
		            money:"10",  
		            fans:"12524",  
		            num:"3",
		            type:"促销",
		            type1:"cuxiao",
		            type2:"cx",
		            type3:"c"
		        }, 
		        {  
		        	sort:"icon_home_collect@3x.png",
		            name:"金融中心",  
		            distance:"6.0",  
		            money:"80",  
		            fans:"15524",  
		            num:"3",
		            type:"金融",
		            type1:"jinrong",
		            type2:"jy",
		            type3:"j"
		        },
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"购物中心",  
		            distance:"6.0",  
		            money:"80",  
		            fans:"15524",  
		            num:"3",
		            type:"促销",
		            type1:"cuxiao",
		            type2:"cx",
		            type3:"c"
		        }
		    ],
		    "广州":[
		        {  
		        	sort:"icon_home_electricity@3x.png",
		            name:"白云机场",  
		            distance:"2.1",  
		            money:"15",  
		            fans:"9415424",  
		            num:"3",
		            type:"交通",
		            type1:"jiaotong",
		            type2:"jt",
		            type3:"j"
		        },  
		        {  
		        	sort:"icon_home_clerk@3x.png",
		            name:"星期天办公大楼",  
		            distance:"2.2",  
		            money:"50",  
		            fans:"9524",  
		            num:"2",
		            type:"文员",
		            type1:"wenyuan",
		            type2:"wy",
		            type3:"w"
		        }, 
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"购物中心",  
		            distance:"5.1",  
		            money:"25",  
		            fans:"65454",  
		            num:"3",
		            type:"促销",
		            type1:"cuxiao",
		            type2:"cx",
		            type3:"c"
		        }, 
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"广州电视塔",  
		            distance:"5.2",  
		            money:"10",  
		            fans:"12524",  
		            num:"3",
		            type:"教育",
		            type1:"jiaoyu",
		            type2:"jy",
		            type3:"j"
		        }, 
		        {  
		        	sort:"icon_home_collect@3x.png",
		            name:"金融中心",  
		            distance:"6.0",  
		            money:"80",  
		            fans:"155243",  
		            num:"3",
		            type:"金融",
		            type1:"jinrong",
		            type2:"jr",
		            type3:"j"
		        },
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"购物中心",  
		            distance:"6.0",  
		            money:"80",  
		            fans:"155244",  
		            num:"2",
		            type:"促销",
		            type1:"cuxiao",
		            type2:"cx",
		            type3:"c"
		        }, 
		        {  
		        	sort:"icon_home_teaching@3x.png",
		            name:"教育中心",  
		            distance:"6.0",  
		            money:"80",  
		            fans:"9524",  
		            num:"3",
		            type:"教育",
		            type1:"jiaoyu",
		            type2:"jy",
		            type3:"j"
		        },
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"购物中心",  
		            distance:"6.0",  
		            money:"80",  
		            fans:"155424",  
		            num:"2",
		            type:"促销",
		            type1:"cuxiao",
		            type2:"cx",
		            type3:"c"
		        }
		    ],
		    "深圳":[
		        {  
		        	sort:"icon_home_ppt@3x.png",
		            name:"深圳火车站",  
		            distance:"2.1",  
		            money:"15",  
		            fans:"515424",  
		            num:"3",
		            type:"交通",
		            type1:"jiaotong",
		            type2:"jt",
		            type3:"j"
		        },  
		        {  
		        	sort:"icon_home_clerk@3x.png",
		            name:"星期天办公大楼",  
		            distance:"2.2",  
		            money:"50",  
		            fans:"9524",  
		            num:"2",
		            type:"文员",
		            type1:"wenyuan",
		            type2:"wy",
		            type3:"w"
		        }, 
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"购物中心",  
		            distance:"5.1",  
		            money:"25",  
		            fans:"65454",  
		            num:"3",
		            type:"促销",
		            type1:"cuxiao",
		            type2:"cx",
		            type3:"c"
		        }, 
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"深圳东辰站",  
		            distance:"5.2",  
		            money:"10",  
		            fans:"12524",  
		            num:"3",
		            type:"交通",
		            type1:"jiaotong",
		            type2:"jt",
		            type3:"j"
		        }, 
		        {  
		        	sort:"icon_home_teaching@3x.png",
		            name:"教育中心",  
		            distance:"6.0",  
		            money:"80",  
		            fans:"9524",  
		            num:"3",
		            type:"教育",
		            type1:"jiaoyu",
		            type2:"jy",
		            type3:"j"
		        },
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"购物中心",  
		            distance:"6.0",  
		            money:"80",  
		            fans:"155424",  
		            num:"2",
		            type:"促销",
		            type1:"cuxiao",
		            type2:"cx",
		            type3:"c"
		        }
		    ],
		    "香港":[
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"购物中心",  
		            distance:"5.1",  
		            money:"25",  
		            fans:"65454",  
		            num:"2",
		            type:"促销",
		            type1:"cuxiao",
		            type2:"cx",
		            type3:"c"
		        }, 
		        {  
		        	sort:"icon_home_teaching@3x.png",
		            name:"教育中心",  
		            distance:"6.0",  
		            money:"80",  
		            fans:"9524",  
		            num:"3",
		            type:"教育",
		            type1:"jiaoyu",
		            type2:"jy",
		            type3:"j"
		        },
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"购物中心",  
		            distance:"6.0",  
		            money:"80",  
		            fans:"155424",  
		            num:"2",
		            type:"促销",
		            type1:"cuxiao",
		            type2:"cx",
		            type3:"c"
		        }
		    ],
		    "澳门":[
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"购物中心",  
		            distance:"5.1",  
		            money:"25",  
		            fans:"65454",  
		            num:"2",
		            type:"促销",
		            type1:"cuxiao",
		            type2:"cx",
		            type3:"c"
		        }, 
		        {  
		        	sort:"icon_home_teaching@3x.png",
		            name:"教育中心",  
		            distance:"6.0",  
		            money:"80",  
		            fans:"9524",  
		            num:"3",
		            type:"教育",
		            type1:"jiaoyu",
		            type2:"jy",
		            type3:"j"
		        },
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"购物中心",  
		            distance:"1.2",  
		            money:"80",  
		            fans:"155424",  
		            num:"2",
		            type:"促销",
		            type1:"cuxiao",
		            type2:"cx",
		            type3:"c"
		        },
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"环球购物中心",  
		            distance:"2.5",  
		            money:"80",  
		            fans:"155424",  
		            num:"2",
		            type:"促销",
		            type1:"cuxiao",
		            type2:"cx",
		            type3:"c"
		        }
		    ],
		    "其他":[
		        {  
		        	sort:"icon_home_ppt@3x.png",
		            name:"火车站",  
		            distance:"2.1",  
		            money:"15",  
		            fans:"515424",  
		            num:"3",
		            type:"交通",
		            type1:"jiaotong",
		            type2:"jt",
		            type3:"j"
		        },  
		        {  
		        	sort:"icon_home_clerk@3x.png",
		            name:"星期天办公大楼",  
		            distance:"2.2",  
		            money:"50",  
		            fans:"9524",  
		            num:"2",
		            type:"文员",
		            type1:"wenyuan",
		            type2:"wy",
		            type3:"w"
		        }, 
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"购物中心",  
		            distance:"5.1",  
		            money:"25",  
		            fans:"65454",  
		            num:"3",
		            type:"促销",
		            type1:"cuxiao",
		            type2:"cx",
		            type3:"c"
		        }, 
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"东辰站",  
		            distance:"5.2",  
		            money:"10",  
		            fans:"12524",  
		            num:"3",
		            type:"交通",
		            type1:"jiaotong",
		            type2:"cx",
		            type3:"c"
		        }, 
		        {  
		        	sort:"icon_home_teaching@3x.png",
		            name:"教育中心",  
		            distance:"6.0",  
		            money:"80",  
		            fans:"9524",  
		            num:"3",
		            type:"教育",
		            type1:"jiaoyu",
		            type2:"jy",
		            type3:"j"
		        },
		        {  
		        	sort:"icon_home_sales@3x.png",
		            name:"购物中心",  
		            distance:"6.0",  
		            money:"80",  
		            fans:"155424",  
		            num:"2",
		            type:"促销",
		            type1:"cuxiao",
		            type2:"cx",
		            type3:"c"
		        }
		    ]
        };
        
        
       